---
title: "Jason Williams, PhD"
---
Water Quality Analyst | Idaho Department of Environmental Quality | jjwill04@gmail.com | jason.williams@deq.idaho.gov

****
### Education

* PhD, 2016, Engineering Science, Washington State University, Department of Civil & Environmental Engineering

* M.S., 2006, SUNY Environmental Science and Forestry School, Department of Environmental and Forest Biology

* B.A., 2004, Biology, Augustana College (Rock Island, IL)

****
### Employment

* Water Quality Analyst, Idaho Department of Environmental Quality (October 2017-present)

* Scientist 3 / Federal Report Coordinator, Idaho Department of Environmental Quality (October 2016-October 2017)

* Environmental Scientist, TerraGraphics Environmental Engineering (2009-2012)

* Research Technician, Department of Biological Sciences, Dartmouth College (2007-2009)

* Aquatic Ecology Technician, NOAA Great Lakes Environmental Research Lab (2004)

****

### Academic Appointments

* Postdoctoral Researcher, National Park Service Air Resources Division & Washington State University (2016)

* Policy Fellowship, USEPA Clean Air Markets Division, Assessment and Communications Branch, Washington D.C. (funded by National Science Foundation) (2013)

* National Science Foundation Fellowship: Nitrogen Systems Policy-oriented Integrated Research and Education (NSPIRE), Washington State University (2012-2014)

* National Science Foundation Research Experience for Undergraduates Exotic Species Program, Eastern Illinois University (2003) 

****

### Peer-Reviewed Publications

1. Williams, J.J., Lynch, J.A., Saros, J.E., Labou, S.G. 2017. [Critical loads of atmospheric N deposition for phytoplankton nutrient limitation shifts in western U.S. mountain lakes.](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecs2.1955) Ecosphere 8(10): e01955. (open access)

2. Williams, J.J., Labou, S.G. 2017. [A database of georeferenced nutrient chemistry data for mountain lakes of the Western United States.](https://www.nature.com/articles/sdata201769) Scientific Data.4: 170069. (open access)

3. Williams, J.J., Chung, S.H., Johansen, A.M., Lamb, B.K., Vaughan, J.K., Beutel, M. 2017. [Evaluation of atmospheric nitrogen deposition model performance in the context of U.S. critical load assessments.](https://www.sciencedirect.com/science/article/pii/S1352231016309426) Atmospheric Environment 150 244-255.

4. Williams, J.J., Nurse, A., Saros, J.E., Riedel, J., Beutel, M. 2016. [Effects ofglaciers on nutrient concentrations and phytoplankton in lakes within the Northern Cascades Mountains (USA).](https://link.springer.com/article/10.1007/s10533-016-0264-y) Biogeochemistry 13(3) 373-376. [ERRATUM](https://link.springer.com/article/10.1007/s10533-016-0282-9)

5. Williams, J.J., Beutel, M., Nurse, A., Moore, B., Hampton, S.E., Saros, JE. 2016. [Phytoplankton responses to nitrogen enrichment in Pacific Northwest, USA mountain lakes.](https://link.springer.com/article/10.1007/s10750-016-2758-y) Hydrobiologia 776(1) 261-276. 

6. Chen, C.Y., Ward, D.M., Williams, J.J., Fisher, N.S. 2016. [Metal bioaccumulation by estuarine foodwebs in New England, USA.](https://www.mdpi.com/2077-1312/4/2/41) Journal of Marine Science and Engineering 4(2) 41. (open access)

7. Chen, C.Y., Borsuk, M.E., Bugge, D.M., Hollweg, T., Balcom, P.H., Ward, D.M., Williams, J.J., Mason, R.P. 2014. [Benthic and pelagic pathways of methylmercury bioaccumulation in estuarine food webs of the Northeast United States.](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0089305) PLOS One 9(2) e89305. (open access)

8. Chen, C.Y., Kamman, N., Williams, J., Bugge, D., Taylor, V., Jackson, B., Miller, E. 2012. [Spatial and temporal variation in mercury bioaccumulation by zooplankton in Lake Champlain (North America).](https://www.sciencedirect.com/science/article/pii/S0269749111005008) Environmental Pollution 161: 343-349. 

9. Williams, J.J., Dutton, J., Chen, C.Y., Fisher, N.S. 2010. [Metal (As, Cd, Hg, and CH3Hg) bioaccumulation from water and food by the benthic amphipod Leptocheirus plumulosus.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3087379/) Environmental Toxicology and Chemistry 29(8) 1755-1761. (open access)

10. Williams, J.J., Pedersen, C.L. 2004. [Diel vertical migration in Daphnia lumholtzi (Sars).](https://www.tandfonline.com/doi/pdf/10.1080/02705060.2004.9664545) Journal of Freshwater Ecology 19(2) 305-311. (open access)

****
### Selected Scientific Presentations (over 20 presentations total)

1. Williams, J.J. March 27, 2019. Tracking Nitrate Contamination and Septic Effluent in an Urbanizing Dryland Agricultural Watershed. National Water Quality Monitoring Conference, Denver, CO.

2. Williams, JJ, Nurse, A, Saros, JE, Riedel, J, Beutel, M. October 18, 2016. Comparison of Nitrate Chemistry and Phytoplankton Between Glacier-fed and Snow-fed Mountain Lakes Within North Cascades National Park. MtnClim Conference, Leavenworth, WA. 

3. Williams, JJ, Beutel, M, Nurse, A. October 19, 2015. Phytoplankton Responses to Nutrient Enrichment in High Elevation Lakes at Mount Rainier, North Cascades, and Olympic National Parks.  9th International Acid Rain Conference, Rochester, NY (poster, won best student poster award)

4. Williams, JJ, Dutton, J, Chen, CY, and Fisher, NS. 4-16-10. Metal (As, Cd, Hg, CH3Hg) 
Bioaccumulation from Water and Food by the Benthic Amphipod Leptocheirus plumulosus. Pacific Northwest Chapter of the Society for Environmental Toxicology and Chemistry 19th Annual Meeting, Port Townsend, WA (oral presentation)

****
### Funded Research Grants ($140,510 total)

1. ‘Nutrient Enrichment Critical Loads of Atmospheric Nitrogen Deposition for Aquatic Ecosystems in the Western U.S.’, J. Williams (co-PI) and M. Beutel (co-PI), 2015-2017, National Park Service Air Resources Division,  $49,671

2. ‘The CEREO News Room: Increasing the Visibility of CEREO Projects Through Interdisciplinary Training and Education’, J. Williams (PI), Todd Norton (co-PI), Lucrezia Paxon (co-PI), Brian Lamb (co-PI), 2014-2015, WSU Center for Environmental Research Education and Outreach (CEREO), $15,000

3. ‘Modeling & Mapping Nitrogen Deposition Rates at NCCN Parks’, J. Williams (co-PI) and M. Beutel (co-PI), 2014-2015, National Park Service NCCN Science Learning Network, $10,040

4. ‘Assessing the Sensitivity of High Elevation NCCN Lakes to Atmospheric Nitrogen Deposition Through Nutrient Enrichment Experiments’, J. Williams (co-PI) and M. Beutel (co-PI), 2013-2016, National Park Service Air Resources Division, $56,879

5. ‘An Assessment of Phytoplankton Community Composition in NCCN Lakes Sensitive to Nitrogen Deposition’, J. Williams (co-PI) and M. Beutel (co-PI), 2013, National Park Service NCCN Science Leaning Network, $4,585

6. ‘Effects of Glaciers on Chemistry of Mountain Lakes in the North Cascades National Park Complex’, J. Williams (PI), 2013, Mazamas Foundation Graduate Student Research Grant, $1,485

7. “Effects of Glaciers on the Chemistry of Mountain Lakes in the North Cascades National Park Complex”, J. Williams (PI), 2013, American Alpine Club Research Grant, $850

8. ‘Horizontal Migration Behavior of Polyphemus pediculus’, J. Williams (PI), Sigma Xi Grant in Aid of Research, 2006,  $1,000

9. ‘Phototaxis and Horizontal Migration by a Predatory Zooplankton’, J. Williams (PI), 2006, Society for Integrative and Comparative Biology Grant in Aid of Research ($1,000)

****

### Awards and Honors
* 2015	Best Student Poster Award, 9th International Conference on Acid Rain, Rochester New York

* 2015	Russ and Anne Fuller Fellowship for Interdisciplinary Research, Washington State University

* 2006	SUNY ESF LeRoy C. Stegeman Award for Invertebrate Biology

* 2004	Glen T. Seaborg Nobel Travel Award (given by the Swedish Council of America)

* 2004	Decatur (IL) Public Schools Young Alumni of the Year Award

* 2002-2003	Rock Island (IL) Conservation Club Scholarship

* 2002-2003	Isabelle Till Scholarship (Augustana College)

* 2000-2004	Founders’ Scholarship (Augustana College)

****
### Selected Training
* 2018		American Heart Association Heartsaver First Aid Training

* 2017	SQL Level 1, Leap Fox Learning, Boise, ID

* 2017	Project Management Fundamentals, Boise State University Center for Professional Development

* 2015	Data Carpentry Workshop, Washington State University

* 2015	Software Carpentry Workshop, Washington State University

* 2013	Wilderness Medical Institute Wilderness First Aid Training 

* 2010		PSMJ Resources Project Management Bootcamp, Seattle WA

* 2009		SAS (Statistical Software) Programming I: Essentials Online Course

* 2009		40-hour HAZWOPER Certification (& 2011, 2012 refreshers)

